hyperskill_project:
  id: 120
  ide_files: https://stepik.org/media/attachments/lesson/388955/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Sat, 25 Jun 2022 09:55:32 UTC
stages:
- id: 648
  step: 10341
  is_completed: true
- id: 649
  step: 10342
  is_completed: true
- id: 650
  step: 10343
  is_completed: true
- id: 651
  step: 10344
  is_completed: true
- id: 652
  step: 10345
  is_completed: false
- id: 653
  step: 10346
  is_completed: false
topics:
  0:
  - title: Write, compile, and run
    theory_id: 3739
  - title: JVM, JRE, and JDK
    theory_id: 3499
  - title: Units of information
    theory_id: 6865
  - title: IDE
    theory_id: 10996
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Computer algorithms
    theory_id: 16547
  - title: The big O notation
    theory_id: 16699
  - title: Best, average and worst cases
    theory_id: 20084
  - title: Data structures
    theory_id: 16927
  - title: Immutability
    theory_id: 7929
  - title: Computer programming
    theory_id: 8739
  - title: Paradigms
    theory_id: 15860
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  - title: Types and variables
    theory_id: 3518
  - title: Comments
    theory_id: 3520
  - title: Scanning the input
    theory_id: 9055
  - title: Coding style conventions
    theory_id: 12411
  1:
  - title: Binary numbers
    theory_id: 5544
  - title: Binary arithmetic
    theory_id: 5630
  - title: Formatted output
    theory_id: 7046
  - title: Writing files
    theory_id: 3652
  - title: What are streams
    theory_id: 5533
  - title: Input streams
    theory_id: 9723
  - title: Output streams
    theory_id: 8837
  - title: Serialization basics
    theory_id: 8147
  - title: Regexps basics
    theory_id: 7580
  - title: Regexps in Java
    theory_id: 3670
  - title: Sets, ranges, alternations
    theory_id: 3674
  - title: Quantifiers
    theory_id: 3687
  - title: Shorthands
    theory_id: 3680
  - title: Regexes in programs
    theory_id: 3696
  - title: Patterns and Matcher
    theory_id: 3712
  - title: Match results
    theory_id: 3716
  - title: Reflection basics
    theory_id: 3609
  - title: Retrieving Class instances
    theory_id: 3554
  - title: Dealing with modifiers
    theory_id: 8104
  - title: Manipulating fields and methods
    theory_id: 8108
  2:
  - title: Generic methods
    theory_id: 3606
  3:
  - title: Queue
    theory_id: 5350
  - title: Recursion basics
    theory_id: 5984
  - title: Decrease and conquer
    theory_id: 14669
  - title: Graph
    theory_id: 15967
  - title: Nodes, cycles and paths
    theory_id: 15968
  - title: Representation of graphs
    theory_id: 15969
  - title: Breadth-first search
    theory_id: 7068
  - title: Tree
    theory_id: 5121
  4:
  - title: Priority queue
    theory_id: 7384
  - title: Weighted graph
    theory_id: 5645
  - title: Shortest path problem
    theory_id: 15223
  - title: Dijkstra's algorithm
    theory_id: 5772
  5:
  - title: Connectivity in graphs
    theory_id: 7956
